services:
  - type: web
    name: discord-video-bot
    env: node
    region: oregon
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg curl python3 && \
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
      chmod a+rx /usr/local/bin/yt-dlp && \
      npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: TOKEN
        sync: false